version: '3'

services:
  hub:
    image: selenium/hub:latest
    platform: linux/amd64
    container_name: hub
    ports:
      - "4442:442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_ENABLE_TRACING=true

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      mode: replicated
      replicas: 4
      restart_policy: 
        condition: on-failure
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  web:
    build: .
    command: tail -f /dev/null
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/user
    environment:
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
